"""initial dB

Revision ID: 7a30983ee82e
Revises: 
Create Date: 2024-09-02 14:03:47.070029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a30983ee82e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_chunks_archive_path', table_name='log_chunks')
    op.drop_index('ix_log_chunks_logtime', table_name='log_chunks')
    op.drop_table('log_chunks')
    op.drop_index('ix_service_archive_path', table_name='service')
    op.drop_index('ix_service_description', table_name='service')
    op.drop_index('ix_service_name', table_name='service')
    op.drop_index('ix_service_source_path', table_name='service')
    op.drop_table('service')
    op.drop_index('ix_application_archive_path', table_name='application')
    op.drop_index('ix_application_name', table_name='application')
    op.drop_table('application')
    op.drop_index('ix_cron_jobs_archive_path', table_name='cron_jobs')
    op.drop_index('ix_cron_jobs_scheduled_execution_time', table_name='cron_jobs')
    op.drop_index('ix_cron_jobs_source_path', table_name='cron_jobs')
    op.drop_table('cron_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('archive_path', sa.VARCHAR(), nullable=True),
    sa.Column('source_path', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_execution_time', sa.DATETIME(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cron_jobs_source_path', 'cron_jobs', ['source_path'], unique=False)
    op.create_index('ix_cron_jobs_scheduled_execution_time', 'cron_jobs', ['scheduled_execution_time'], unique=False)
    op.create_index('ix_cron_jobs_archive_path', 'cron_jobs', ['archive_path'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('archive_path', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_name', 'application', ['name'], unique=False)
    op.create_index('ix_application_archive_path', 'application', ['archive_path'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('archive_path', sa.VARCHAR(), nullable=True),
    sa.Column('source_path', sa.VARCHAR(), nullable=True),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_source_path', 'service', ['source_path'], unique=False)
    op.create_index('ix_service_name', 'service', ['name'], unique=False)
    op.create_index('ix_service_description', 'service', ['description'], unique=False)
    op.create_index('ix_service_archive_path', 'service', ['archive_path'], unique=False)
    op.create_table('log_chunks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('archive_path', sa.VARCHAR(), nullable=True),
    sa.Column('logtime', sa.DATETIME(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_chunks_logtime', 'log_chunks', ['logtime'], unique=False)
    op.create_index('ix_log_chunks_archive_path', 'log_chunks', ['archive_path'], unique=False)
    # ### end Alembic commands ###
